vpc_id                     = "vpc-0b39de2109d507d42"
security_group_name        = "gryukhanyan-sg-tf"
security_group_description = "Grig security group from tf"
launch_template_name       = "gryukhanyan_launch_template_tf"
instance_type_tf           = "t2.micro"
key_pair_tf                = "sunnyscool"
availability_zone_tf       = "us-east-2a"